apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi  # Specify the size of the volume
  accessModes:
    - ReadWriteOnce  # This volume can be mounted as read-write by a single node
  hostPath:          # Use a directory on the host
    path: E:\DataStorage  # Change this to your local directory
