apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Specify the access mode
  resources:
    requests:
      storage: 1Gi  # Specify the size of the claim
